version: '3.8'
services:
  postgres:
    image: postgres:16
    ports:
      - "55432:5432"
    environment:
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
